var searchData=
[
  ['findedge_0',['findedge',['../functions_8h.html#a8d09c81fc1ab03faa75ab325992d8b65',1,'findEdge(Graph&lt; Location, Distance &gt; *g, const std::string &amp;sourceId, const std::string &amp;destinationId):&#160;functions.h'],['../graph_8cpp.html#af20ae45414488fae507d5b36918231f2',1,'findEdge(Graph&lt; Location, Distance &gt; *g, const string &amp;sourceId, const string &amp;destinationId):&#160;graph.cpp']]],
  ['findpathfordrivingwalking_1',['findpathfordrivingwalking',['../algorithms_8cpp.html#ab31c41333f26435498ac2db1c2a7c960',1,'findPathForDrivingWalking(Graph&lt; Location, Distance &gt; *g, Vertex&lt; Location, Distance &gt; *start, Vertex&lt; Location, Distance &gt; *end, const vector&lt; Vertex&lt; Location, Distance &gt; * &gt; &amp;nodesToAvoid, const vector&lt; Edge&lt; Location, Distance &gt; * &gt; &amp;edgesToAvoid, const double maxWalkingTime, const bool secondBest):&#160;algorithms.cpp'],['../functions_8h.html#af31ced769379ca604e4d6872f3ce65e2',1,'findPathForDrivingWalking(Graph&lt; Location, Distance &gt; *g, Vertex&lt; Location, Distance &gt; *start, Vertex&lt; Location, Distance &gt; *end, const std::vector&lt; Vertex&lt; Location, Distance &gt; * &gt; &amp;nodesToAvoid, const std::vector&lt; Edge&lt; Location, Distance &gt; * &gt; &amp;edgesToAvoid, const double maxWalkingTime, const bool secondBest):&#160;functions.h']]],
  ['findshortestpath_2',['findshortestpath',['../algorithms_8cpp.html#a985ffdf902acdf598c90b92ba2ac64a5',1,'findShortestPath(Graph&lt; Location, Distance &gt; *g, Vertex&lt; Location, Distance &gt; *start, Vertex&lt; Location, Distance &gt; *end, const vector&lt; Vertex&lt; Location, Distance &gt; * &gt; &amp;nodesToAvoid, const vector&lt; Edge&lt; Location, Distance &gt; * &gt; &amp;edgesToAvoid, bool driving):&#160;algorithms.cpp'],['../functions_8h.html#a6cb94a190a65a820bd6aacf72fb94118',1,'findShortestPath(Graph&lt; Location, Distance &gt; *g, Vertex&lt; Location, Distance &gt; *start, Vertex&lt; Location, Distance &gt; *end, const std::vector&lt; Vertex&lt; Location, Distance &gt; * &gt; &amp;nodesToAvoid, const std::vector&lt; Edge&lt; Location, Distance &gt; * &gt; &amp;edgesToAvoid, bool driving):&#160;functions.h']]],
  ['findshortestpathmultiplenodes_3',['findshortestpathmultiplenodes',['../algorithms_8cpp.html#a573c2a7827f07facf09485b322200095',1,'findShortestPathMultipleNodes(Graph&lt; Location, Distance &gt; *g, const vector&lt; Vertex&lt; Location, Distance &gt; * &gt; nodesToConnect, const vector&lt; Vertex&lt; Location, Distance &gt; * &gt; &amp;nodesToAvoid, const vector&lt; Edge&lt; Location, Distance &gt; * &gt; &amp;edgesToAvoid, bool driving):&#160;algorithms.cpp'],['../functions_8h.html#a856dc21469395044aca7c1570aadc86d',1,'findShortestPathMultipleNodes(Graph&lt; Location, Distance &gt; *g, const std::vector&lt; Vertex&lt; Location, Distance &gt; * &gt; nodesToConnect, const std::vector&lt; Vertex&lt; Location, Distance &gt; * &gt; &amp;nodesToAvoid, const std::vector&lt; Edge&lt; Location, Distance &gt; * &gt; &amp;edgesToAvoid, bool driving):&#160;functions.h']]],
  ['findvertex_4',['findvertex',['../functions_8h.html#acfbc9cedb3f13b13d3e46c4343111670',1,'findVertex(Graph&lt; Location, Distance &gt; *g, const std::string &amp;identifier):&#160;functions.h'],['../graph_8cpp.html#a0d47129fccd3a8b7607a36c6512ab0ed',1,'findVertex(Graph&lt; Location, Distance &gt; *g, const string &amp;identifier):&#160;graph.cpp']]],
  ['findvertexbycode_5',['findVertexByCode',['../graph_8cpp.html#a131d689111c25671aa9634f2992931a9',1,'graph.cpp']]],
  ['findvertexbyid_6',['findVertexById',['../graph_8cpp.html#a65926860d0b4679089ebbd0d3aa28c67',1,'graph.cpp']]],
  ['functions_2eh_7',['functions.h',['../functions_8h.html',1,'']]]
];
